export interface VulnCard {
  id: string;
  code: string;
  title: string;
  family: "Web" | "API" | "LLM" | "Cloud";
  cwe?: string;
  summary: string;
  signals: string[];
  tests: string[];
  fix: string;
  refs: { label: string; url: string }[];
}

export const ENCYCLOPEDIA: VulnCard[] = [
  // ---------- OWASP Web Top 10 (2021) ----------
  {
    id: "web-a01", code: "A01:2021", title: "Broken Access Control", family: "Web", cwe: "CWE-284",
    summary: "The app fails to enforce restrictions on what authenticated users can do. IDOR, force-browsing, missing function-level checks.",
    signals: ["Sequential/predictable IDs in URLs or bodies", "Admin routes reachable with a normal token", "Different roles receive identical responses"],
    tests: ["Swap object IDs across two accounts you own", "Replay privileged requests with a low-priv session", "Diff Autorize matrix across roles"],
    fix: "Enforce authorization on the server for every object + action. Deny by default. Log access decisions.",
    refs: [{ label: "OWASP A01", url: "https://owasp.org/Top10/A01_2021-Broken_Access_Control/" }],
  },
  {
    id: "web-a02", code: "A02:2021", title: "Cryptographic Failures", family: "Web", cwe: "CWE-311",
    summary: "Weak transport crypto, plaintext storage of secrets, predictable tokens, weak JWT signing.",
    signals: ["No HSTS or mixed content", "Guessable session or reset tokens", "JWT alg=none or weak HS256 secret"],
    tests: ["testssl.sh + sslscan", "jwt_tool crack against known wordlist", "Sample 20 reset tokens — check entropy"],
    fix: "TLS 1.2+ only, HSTS preload, KMS-backed secrets, strong asymmetric signing with key rotation.",
    refs: [{ label: "OWASP A02", url: "https://owasp.org/Top10/A02_2021-Cryptographic_Failures/" }],
  },
  {
    id: "web-a03", code: "A03:2021", title: "Injection", family: "Web", cwe: "CWE-79",
    summary: "SQL, NoSQL, OS-command, LDAP, template, and XSS. Untrusted input reaches an interpreter.",
    signals: ["Errors leak SQL syntax", "Time-based delays on payloads", "Payload reflected unescaped"],
    tests: ["sqlmap on isolated params", "dalfox / XSStrike for reflected/DOM XSS", "commix on shell-adjacent endpoints"],
    fix: "Parameterized queries, output encoding contextual to sink, strict CSP, allow-list template engines.",
    refs: [{ label: "OWASP A03", url: "https://owasp.org/Top10/A03_2021-Injection/" }],
  },
  {
    id: "web-a04", code: "A04:2021", title: "Insecure Design", family: "Web", cwe: "CWE-657",
    summary: "Business-logic flaws — race conditions, coupon reuse, price tampering, workflow skipping.",
    signals: ["Server trusts client-supplied price / quantity", "No idempotency key on money endpoints", "Workflow can be jumped by hitting the final URL directly"],
    tests: ["Turbo Intruder single-packet race on checkout", "Replay coupon 50× concurrently", "Skip step 2 of a wizard"],
    fix: "Threat-model the workflow. Enforce state machine server-side. Idempotency keys on writes.",
    refs: [{ label: "OWASP A04", url: "https://owasp.org/Top10/A04_2021-Insecure_Design/" }],
  },
  {
    id: "web-a05", code: "A05:2021", title: "Security Misconfiguration", family: "Web", cwe: "CWE-16",
    summary: "Defaults, verbose errors, permissive CORS, missing headers, exposed admin panels.",
    signals: ["Stack traces in responses", "Access-Control-Allow-Origin: *", "Missing CSP / HSTS / X-Content-Type-Options"],
    tests: ["nikto + nuclei misconfig tags", "CORScanner", "Manual header audit"],
    fix: "Hardened baselines per env, error handlers that don't leak, least-privilege CORS.",
    refs: [{ label: "OWASP A05", url: "https://owasp.org/Top10/A05_2021-Security_Misconfiguration/" }],
  },
  {
    id: "web-a06", code: "A06:2021", title: "Vulnerable & Outdated Components", family: "Web", cwe: "CWE-1104",
    summary: "Known-CVE libraries, EoL runtimes, unpatched CMSs.",
    signals: ["Version-disclosing headers", "Old jQuery / Rails / Spring in JS or errors", "wpscan hits"],
    tests: ["retire.js on bundles", "nuclei -tags cve", "SBOM diff vs. NVD"],
    fix: "Dependency inventory, automated update pipeline, virtual patching via WAF as a stop-gap.",
    refs: [{ label: "OWASP A06", url: "https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/" }],
  },
  {
    id: "web-a07", code: "A07:2021", title: "Identification & Authentication Failures", family: "Web", cwe: "CWE-287",
    summary: "Weak login, credential stuffing, session fixation, weak MFA, predictable reset tokens.",
    signals: ["Different response for valid vs invalid username", "Rate-limit missing on /login", "Reset token in URL and reusable"],
    tests: ["Timing + body diff on user enum", "Rate-limit sweep on auth", "Reset flow: host header injection, token entropy, race"],
    fix: "Uniform login responses, WebAuthn, secure session cookies, one-time high-entropy reset tokens.",
    refs: [{ label: "OWASP A07", url: "https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/" }],
  },
  {
    id: "web-a08", code: "A08:2021", title: "Software & Data Integrity Failures", family: "Web", cwe: "CWE-345",
    summary: "Insecure deserialization, unsigned updates, dependency confusion, CI/CD supply chain.",
    signals: ["Base64 blobs that look like serialized objects", "Auto-updater without signature check", "Private package names resolvable on public registry"],
    tests: ["ysoserial gadgets for Java/.NET", "Register internal names on npm/pypi (in a sandbox)"],
    fix: "Signed artifacts, SLSA-style build provenance, scoped/private registries.",
    refs: [{ label: "OWASP A08", url: "https://owasp.org/Top10/A08_2021-Software_and_Data_Integrity_Failures/" }],
  },
  {
    id: "web-a09", code: "A09:2021", title: "Security Logging & Monitoring Failures", family: "Web", cwe: "CWE-778",
    summary: "High-signal actions go unlogged or unalerted, letting attackers dwell.",
    signals: ["100 failed logins produce no lockout / alert", "Admin actions have no audit trail", "Logs contain PII / secrets"],
    tests: ["Baseline noisy action + wait for triage response", "Read your own audit log for gaps"],
    fix: "Central SIEM, structured logs, alerting on abuse patterns, log-injection sanitization.",
    refs: [{ label: "OWASP A09", url: "https://owasp.org/Top10/A09_2021-Security_Logging_and_Monitoring_Failures/" }],
  },
  {
    id: "web-a10", code: "A10:2021", title: "Server-Side Request Forgery (SSRF)", family: "Web", cwe: "CWE-918",
    summary: "The server fetches an attacker-controlled URL — pivot to internal services & cloud metadata.",
    signals: ["Webhook / import / preview / PDF-render endpoints", "URL parameter accepted verbatim"],
    tests: ["interactsh OOB callback", "169.254.169.254 for AWS/GCP/Azure metadata", "SSRFmap gopher/dict"],
    fix: "Allow-list egress, block link-local + private ranges, use signed URLs, IMDSv2 only.",
    refs: [{ label: "OWASP A10", url: "https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_(SSRF)/" }],
  },
  // ---------- OWASP API Top 10 (2023) ----------
  {
    id: "api1", code: "API1:2023", title: "Broken Object Level Authorization (BOLA)", family: "API", cwe: "CWE-639",
    summary: "The most common API bug: object-scope checks missing. Swap IDs, get someone else's data.",
    signals: ["Numeric/UUID IDs in every path", "Same endpoint returns any user's data based on ID"],
    tests: ["Two accounts, swap IDs, diff responses", "Autorize matrix across two sessions"],
    fix: "Server-side scope check per object per action. Prefer opaque IDs + ownership joins.",
    refs: [{ label: "OWASP API1", url: "https://owasp.org/API-Security/editions/2023/en/0xa1-broken-object-level-authorization/" }],
  },
  {
    id: "api2", code: "API2:2023", title: "Broken Authentication", family: "API",
    summary: "Weak JWT, missing refresh rotation, guessable session IDs, OAuth misimplementation.",
    signals: ["alg=none accepted", "kid path traversal", "No refresh rotation"],
    tests: ["jwt_tool full audit", "OAuth flow review with Burp EsPReSSO"],
    fix: "Rotate refresh tokens, pin algorithms, verify audience/issuer, PKCE for public clients.",
    refs: [{ label: "OWASP API2", url: "https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/" }],
  },
  {
    id: "api3", code: "API3:2023", title: "Broken Object Property Level Authorization", family: "API",
    summary: "Mass assignment + excessive data exposure. Extra fields sneak into writes; responses over-fetch.",
    signals: ["PATCH accepts fields not in the UI", "Response includes internal flags (isAdmin, price)"],
    tests: ["Add {role:'admin'} to update requests", "Diff response payload vs UI fields"],
    fix: "Explicit allow-list DTOs on read + write. Never trust ORM 'update all attributes'.",
    refs: [{ label: "OWASP API3", url: "https://owasp.org/API-Security/editions/2023/en/0xa3-broken-object-property-level-authorization/" }],
  },
  {
    id: "api4", code: "API4:2023", title: "Unrestricted Resource Consumption", family: "API",
    summary: "No rate limits, unbounded pagination, expensive GraphQL — cost/DoS.",
    signals: ["No 429 under sustained load", "GraphQL alias/nesting bombs succeed"],
    tests: ["Rate sweep + burst test", "GraphQL alias bomb, deep nesting, batching"],
    fix: "Per-token + per-IP limits, GraphQL cost analysis + depth limits, pagination caps.",
    refs: [{ label: "OWASP API4", url: "https://owasp.org/API-Security/editions/2023/en/0xa4-unrestricted-resource-consumption/" }],
  },
  {
    id: "api5", code: "API5:2023", title: "Broken Function Level Authorization", family: "API",
    summary: "Admin endpoints callable with normal-user tokens. Vertical privilege escalation.",
    signals: ["/admin/* returns 200 for any authenticated user", "DELETE reachable when only GET/POST are in the UI"],
    tests: ["Call admin routes with low-priv token", "Method fuzz on privileged routes"],
    fix: "Role check as a framework-level default, not per-handler.",
    refs: [{ label: "OWASP API5", url: "https://owasp.org/API-Security/editions/2023/en/0xa5-broken-function-level-authorization/" }],
  },
  {
    id: "api6", code: "API6:2023", title: "Unrestricted Access to Sensitive Business Flows", family: "API",
    summary: "Automation of human-only flows (bulk signup, ticket scalping, referral abuse).",
    signals: ["No captcha / device check on high-value flow", "Referral bonus applies to same-device signups"],
    tests: ["Script the flow 100× with rotating identities you own", "Bypass captcha via headless"],
    fix: "Risk-based friction (device fingerprinting, behavioral analysis, per-account caps).",
    refs: [{ label: "OWASP API6", url: "https://owasp.org/API-Security/editions/2023/en/0xa6-unrestricted-access-to-sensitive-business-flows/" }],
  },
  {
    id: "api7", code: "API7:2023", title: "Server-Side Request Forgery (API)", family: "API",
    summary: "Same as web SSRF but via API endpoints — webhooks, imports, previews.",
    signals: ["Any endpoint that takes a URL and fetches it"],
    tests: ["interactsh OOB", "Cloud metadata pivot"],
    fix: "Egress allow-list, block link-local, IMDSv2 only.",
    refs: [{ label: "OWASP API7", url: "https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/" }],
  },
  {
    id: "api8", code: "API8:2023", title: "Security Misconfiguration", family: "API",
    summary: "Verbose errors, permissive CORS, unnecessary methods, outdated TLS on APIs.",
    signals: ["OPTIONS/TRACE enabled", "Wildcard CORS with credentials"],
    tests: ["nuclei -tags misconfig,api", "Manual header + method audit"],
    fix: "Baseline per-env, explicit CORS, WAF in front.",
    refs: [{ label: "OWASP API8", url: "https://owasp.org/API-Security/editions/2023/en/0xa8-security-misconfiguration/" }],
  },
  {
    id: "api9", code: "API9:2023", title: "Improper Inventory Management", family: "API",
    summary: "Old /v1 still live next to /v3. Staging/beta exposed. Deprecated docs.",
    signals: ["/v1/* returns different data than /v3/*", "internal.api.target.com reachable"],
    tests: ["Version pivot fuzz", "DNS + cert enum for staging"],
    fix: "Retire old versions on a schedule, environment isolation, gateway inventory.",
    refs: [{ label: "OWASP API9", url: "https://owasp.org/API-Security/editions/2023/en/0xa9-improper-inventory-management/" }],
  },
  {
    id: "api10", code: "API10:2023", title: "Unsafe Consumption of 3rd-Party APIs", family: "API",
    summary: "The target trusts an upstream response blindly — smuggle payloads via the upstream.",
    signals: ["Response fields from a partner API rendered without validation"],
    tests: ["If you control an integration, return XSS/RCE bait in your response"],
    fix: "Validate + sanitize responses like any user input. Don't 'trust the vendor'.",
    refs: [{ label: "OWASP API10", url: "https://owasp.org/API-Security/editions/2023/en/0xaa-unsafe-consumption-of-apis/" }],
  },
  // ---------- OWASP LLM Top 10 (2025) ----------
  {
    id: "llm01", code: "LLM01:2025", title: "Prompt Injection", family: "LLM",
    summary: "Direct or indirect attacker input overrides the system prompt or hijacks tool calls.",
    signals: ["Model ingests user-supplied documents / URLs / emails", "Tool-calling agent"],
    tests: ["Direct: 'ignore previous instructions…'", "Indirect: plant payload in a URL the model fetches", "Encoding evasion: base64 / homoglyph"],
    fix: "Segregate trusted vs untrusted context, structured output only, human-in-loop on side-effect tools, guardrail models.",
    refs: [{ label: "OWASP LLM01", url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/" }],
  },
  {
    id: "llm02", code: "LLM02:2025", title: "Sensitive Information Disclosure", family: "LLM",
    summary: "Model leaks system prompt, other users' RAG data, PII memorized in training/fine-tune.",
    signals: ["Shared vector store across tenants", "No output filter for secrets"],
    tests: ["'Repeat the text above verbatim…'", "Cross-tenant retrieval probe"],
    fix: "Per-tenant retrieval scoping, DLP on output, don't put secrets in the system prompt.",
    refs: [{ label: "OWASP LLM02", url: "https://genai.owasp.org/llmrisk/llm02-sensitive-information-disclosure/" }],
  },
  {
    id: "llm03", code: "LLM03:2025", title: "Supply Chain", family: "LLM",
    summary: "Poisoned weights, malicious HuggingFace models, untrusted embeddings, backdoored plugins.",
    signals: ["Model pulled by name at runtime with no pin/hash", "Community plugins auto-installed"],
    tests: ["Audit model source, verify SHA", "Review plugin permissions"],
    fix: "Pin model hashes, private registry, provenance (Sigstore/SLSA), plugin allow-list.",
    refs: [{ label: "OWASP LLM03", url: "https://genai.owasp.org/llmrisk/llm03-supply-chain/" }],
  },
  {
    id: "llm04", code: "LLM04:2025", title: "Data & Model Poisoning", family: "LLM",
    summary: "Attacker-controlled content ends up in fine-tune or RAG store, biasing the model.",
    signals: ["Public form / feedback feeds retraining", "User uploads land in shared index"],
    tests: ["Submit distinctive canary; check if later retrievable in someone else's session"],
    fix: "Provenance on training data, per-tenant indices, moderation before ingestion.",
    refs: [{ label: "OWASP LLM04", url: "https://genai.owasp.org/llmrisk/llm04-data-and-model-poisoning/" }],
  },
  {
    id: "llm05", code: "LLM05:2025", title: "Improper Output Handling", family: "LLM",
    summary: "Model output rendered as HTML/Markdown → XSS. Passed to shell/SQL → RCE/SQLi.",
    signals: ["Assistant output rendered without sanitization", "Model output used as function args"],
    tests: ["Ask model to emit <img onerror>", "Coax tool call with $(id) argument"],
    fix: "Treat LLM output as untrusted user input downstream. Parameterize + sanitize per sink.",
    refs: [{ label: "OWASP LLM05", url: "https://genai.owasp.org/llmrisk/llm05-improper-output-handling/" }],
  },
  {
    id: "llm06", code: "LLM06:2025", title: "Excessive Agency", family: "LLM",
    summary: "Agent has tools that spend money, send email, or hit internal APIs without human approval.",
    signals: ["Autonomous tool loops", "Broad scopes on service accounts the agent uses"],
    tests: ["Enumerate tools; try to trigger side-effect tool via injected instructions"],
    fix: "Least-privilege tool scopes, human-in-loop confirmations, per-tool rate limits.",
    refs: [{ label: "OWASP LLM06", url: "https://genai.owasp.org/llmrisk/llm06-excessive-agency/" }],
  },
  {
    id: "llm07", code: "LLM07:2025", title: "System Prompt Leakage", family: "LLM",
    summary: "System prompt exposes tool keys, business rules, or guardrail bypass strings.",
    signals: ["System prompt contains secrets / URLs / model overrides"],
    tests: ["Layered leak probes; translation + roleplay bypasses"],
    fix: "Never put secrets in the system prompt. Assume it will leak.",
    refs: [{ label: "OWASP LLM07", url: "https://genai.owasp.org/llmrisk/llm07-system-prompt-leakage/" }],
  },
  {
    id: "llm08", code: "LLM08:2025", title: "Vector & Embedding Weaknesses", family: "LLM",
    summary: "Embedding inversion, cross-tenant retrieval, unauthenticated vector-DB endpoints.",
    signals: ["Vector DB exposed on public port", "Shared collection across tenants"],
    tests: ["curl Qdrant/Weaviate/Pinecone default paths", "Adversarial nearest-neighbor payload"],
    fix: "Authenticate vector DB, per-tenant collections, encrypted embeddings.",
    refs: [{ label: "OWASP LLM08", url: "https://genai.owasp.org/llmrisk/llm08-vector-and-embedding-weaknesses/" }],
  },
  {
    id: "llm09", code: "LLM09:2025", title: "Misinformation & Over-Reliance", family: "LLM",
    summary: "Confident hallucination → downstream harm (fake package names → RCE via install).",
    signals: ["Users execute model output blindly (code, shell, SQL)"],
    tests: ["Ask for niche package/API name; check if fabricated"],
    fix: "Ground in retrieval + citation, warn on low confidence, require review for actions.",
    refs: [{ label: "OWASP LLM09", url: "https://genai.owasp.org/llmrisk/llm09-misinformation/" }],
  },
  {
    id: "llm10", code: "LLM10:2025", title: "Unbounded Consumption", family: "LLM",
    summary: "Cost / rate DoS via huge prompts, recursive tool loops, no max_tokens cap.",
    signals: ["No per-user token/quota limit", "Agent can call itself"],
    tests: ["Request 100k tokens", "Trigger a tool loop in a sandbox you own"],
    fix: "Per-user quotas, hard token/tool-call caps, timeout the agent loop.",
    refs: [{ label: "OWASP LLM10", url: "https://genai.owasp.org/llmrisk/llm10-unbounded-consumption/" }],
  },
];

export const FAMILIES = ["Web", "API", "LLM", "Cloud"] as const;
