import { useEffect, useMemo, useState } from "react";
import { marked } from "marked";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Download, FileText, Printer, Copy, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { downloadMarkdown } from "@/lib/export";

interface Props {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  initialMarkdown: string;
  filenameBase: string; // no extension
  title: string;
  hint?: string;
}

marked.setOptions({ gfm: true, breaks: false });

const PRINT_CSS = `
  @page { size: A4; margin: 22mm 18mm; }
  * { box-sizing: border-box; }
  html, body { padding: 0; margin: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #0f172a; line-height: 1.55; font-size: 11pt; }
  .cover { border-bottom: 3px solid #0ea5e9; padding-bottom: 14pt; margin-bottom: 18pt; }
  .cover .eyebrow { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: .18em; font-size: 8pt; color: #0284c7; margin-bottom: 6pt; }
  .cover .classification { font-family: ui-monospace, monospace; font-size: 8pt; color: #dc2626; letter-spacing: .12em; }
  h1 { font-size: 22pt; margin: 0 0 8pt; color: #0f172a; letter-spacing: -0.01em; }
  h2 { font-size: 15pt; margin: 22pt 0 8pt; padding-bottom: 4pt; border-bottom: 1px solid #cbd5e1; color: #0f172a; page-break-after: avoid; }
  h3 { font-size: 12pt; margin: 14pt 0 6pt; color: #0369a1; page-break-after: avoid; }
  h4 { font-size: 11pt; margin: 10pt 0 4pt; color: #334155; }
  p, ul, ol { margin: 4pt 0 8pt; }
  ul, ol { padding-left: 20pt; }
  li { margin: 2pt 0; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 9pt; background: #f1f5f9; padding: 1pt 4pt; border-radius: 3px; color: #0f172a; }
  pre { background: #0f172a; color: #e2e8f0; padding: 10pt; border-radius: 4pt; overflow: hidden; white-space: pre-wrap; word-break: break-word; font-size: 8.5pt; page-break-inside: avoid; }
  pre code { background: transparent; color: inherit; padding: 0; }
  blockquote { border-left: 3px solid #0ea5e9; margin: 8pt 0; padding: 4pt 10pt; background: #f0f9ff; color: #0c4a6e; font-style: italic; }
  table { border-collapse: collapse; width: 100%; margin: 8pt 0; font-size: 9.5pt; page-break-inside: avoid; }
  th, td { border: 1px solid #cbd5e1; padding: 5pt 7pt; text-align: left; vertical-align: top; }
  th { background: #f1f5f9; font-weight: 600; color: #0f172a; }
  hr { border: none; border-top: 1px solid #cbd5e1; margin: 14pt 0; }
  a { color: #0284c7; text-decoration: none; }
  img { max-width: 100%; }
  .footer { margin-top: 24pt; padding-top: 8pt; border-top: 1px solid #cbd5e1; font-size: 8pt; color: #64748b; text-align: center; font-family: ui-monospace, monospace; }
`;

function buildPrintHtml(title: string, bodyHtml: string): string {
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title.replace(/[<>&]/g, "")}</title><style>${PRINT_CSS}</style></head>
<body>
  <div class="cover">
    <div class="eyebrow">Security Assessment · Confidential</div>
    <div class="classification">AUTHORIZED TESTING ONLY — HANDLE PER PROGRAM RULES</div>
  </div>
  ${bodyHtml}
  <div class="footer">Generated by Recon Workbench · ${new Date().toLocaleString()}</div>
</body></html>`;
}

export function ReportPreview({ open, onOpenChange, initialMarkdown, filenameBase, title, hint }: Props) {
  const [md, setMd] = useState(initialMarkdown);
  useEffect(() => { if (open) setMd(initialMarkdown); }, [open, initialMarkdown]);

  const html = useMemo(() => marked.parse(md) as string, [md]);

  function downloadMd() {
    downloadMarkdown(`${filenameBase}.md`, md);
    toast.success("Markdown downloaded");
  }

  function copyMd() {
    navigator.clipboard.writeText(md).then(
      () => toast.success("Copied to clipboard"),
      () => toast.error("Copy failed"),
    );
  }

  function exportPdf() {
    const w = window.open("", "_blank", "width=900,height=1100");
    if (!w) { toast.error("Popup blocked — allow popups to export PDF"); return; }
    w.document.open();
    w.document.write(buildPrintHtml(title, html));
    w.document.close();
    // Give the new window time to layout before invoking print
    const trigger = () => { try { w.focus(); w.print(); } catch { /* ignore */ } };
    if (w.document.readyState === "complete") setTimeout(trigger, 250);
    else w.addEventListener("load", () => setTimeout(trigger, 250));
    toast.info("Opened print dialog — choose 'Save as PDF'");
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-6xl w-[95vw] max-h-[92vh] flex flex-col p-0 gap-0">
        <DialogHeader className="px-6 pt-5 pb-3 border-b border-border/60">
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-4 w-4 text-primary" /> {title}
          </DialogTitle>
          {hint && <p className="text-xs text-muted-foreground">{hint}</p>}
        </DialogHeader>

        <Tabs defaultValue="edit" className="flex-1 flex flex-col min-h-0">
          <div className="flex items-center justify-between px-6 pt-3 gap-3 flex-wrap">
            <TabsList>
              <TabsTrigger value="edit"><Sparkles className="h-3.5 w-3.5 mr-1.5" /> Edit</TabsTrigger>
              <TabsTrigger value="preview">Preview</TabsTrigger>
              <TabsTrigger value="split">Split</TabsTrigger>
            </TabsList>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-[11px] mono text-muted-foreground">
                {md.length.toLocaleString()} chars · {md.split(/\s+/).filter(Boolean).length.toLocaleString()} words
              </span>
              <Button size="sm" variant="ghost" onClick={copyMd}><Copy className="h-3.5 w-3.5 mr-1.5" /> Copy</Button>
              <Button size="sm" variant="outline" onClick={downloadMd}><Download className="h-3.5 w-3.5 mr-1.5" /> Markdown</Button>
              <Button size="sm" onClick={exportPdf}><Printer className="h-3.5 w-3.5 mr-1.5" /> Export PDF</Button>
            </div>
          </div>

          <TabsContent value="edit" className="flex-1 min-h-0 px-6 pb-6 pt-3 m-0">
            <Textarea
              value={md}
              onChange={(e) => setMd(e.target.value)}
              className="mono text-xs h-full min-h-[60vh] resize-none"
              spellCheck={false}
            />
          </TabsContent>

          <TabsContent value="preview" className="flex-1 min-h-0 px-6 pb-6 pt-3 m-0 overflow-auto">
            <PreviewPane html={html} />
          </TabsContent>

          <TabsContent value="split" className="flex-1 min-h-0 px-6 pb-6 pt-3 m-0">
            <div className="grid md:grid-cols-2 gap-3 h-full min-h-[60vh]">
              <Textarea
                value={md}
                onChange={(e) => setMd(e.target.value)}
                className="mono text-xs h-full resize-none"
                spellCheck={false}
              />
              <div className="overflow-auto rounded-md border border-border/60 bg-background">
                <PreviewPane html={html} />
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}

function PreviewPane({ html }: { html: string }) {
  return (
    <article
      className="prose prose-invert prose-sm max-w-none px-2 py-1
        prose-headings:display prose-headings:text-foreground
        prose-h1:text-2xl prose-h1:border-b prose-h1:border-primary/40 prose-h1:pb-2
        prose-h2:text-xl prose-h2:text-primary prose-h2:mt-6
        prose-h3:text-base prose-h3:text-accent
        prose-code:text-primary prose-code:bg-muted/60 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:before:content-none prose-code:after:content-none
        prose-pre:bg-muted/40 prose-pre:border prose-pre:border-border/60
        prose-a:text-primary prose-blockquote:border-primary prose-blockquote:text-muted-foreground
        prose-table:text-xs prose-th:bg-muted/40"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
